# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Geary
email: willgeary@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Personal blog about a few of the things I enjoy: data science, cities and bikes
baseurl: "" # the subpath of your site, e.g. /blog
url: http://willgeary.github.io # the base hostname & protocol for your site
twitter_username: wgeary
github_username:  willgeary
linkedin_username: willgeary
facebook_username: wcgeary

# Build settings
markdown: kramdown
